loadtxt raises TypeError instead of ValueError when fname is wrong type
-----------------------------------------------------------------------
``numpy.loadtxt`` now raises a `TypeError` instead of a `ValueError` when the
type of the ``fname`` parameter is incorrect.

Previous behavior::

    >>> np.loadtxt(1)  # doctest: +SKIP
    Traceback (most recent call last):
       ...
    ValueError: fname must be a string, file handle, or generator

Current behavior::

    >>> np.loadtxt(1)  # doctest: +SKIP
    Traceback (most recent call last):
       ...
    TypeError: fname must be a string, filehandle, list of strings,
    or generator. Got <class 'int'> instead.
